foreground            #F1A997
background            #0F1728
cursor                #F1A997
selection_background  #A33355

# Black / Grey
color0  #131D32
color8  #293249

# Red
color1  #271B29
color9  #524954

# Green
color2  #1F2B4B
color10 #4C556F

# Yellow
color3  #852B4B
color11 #9D556F

# Blue
color4  #AC4766
color12 #B55C77

# Magenta
color5  #CA3D6A
color13 #D56488

# Cyan
color6  #DD7975
color14 #E49491

# White
color7  #F1A997
color15 #F4BAAC
