foreground            {{foreground}}
background            {{background | darken(0.2)}}
cursor                {{cursor}}
selection_background  {{color4}}

# Black / Grey
color0  {{color0}}
color8  {{color8}}

# Red
color1  {{color1}}
color9  {{color9 | lighten(0.2) }}

# Green
color2  {{color2}}
color10 {{color10 | lighten(0.2) }}

# Yellow
color3  {{color3}}
color11 {{color11 | lighten(0.2) }}

# Blue
color4  {{color4 | lighten(0.1) }}
color12 {{color12 | lighten(0.2) }}

# Magenta
color5  {{color5}}
color13 {{color13 | lighten(0.2) }}

# Cyan
color6  {{color6}}
color14 {{color14 | lighten(0.2) }}

# White
color7  {{color7}}
color15 {{color15 | lighten(0.2) }}
