-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "capitaine-cursors")
hl.env("XCURSOR_SIZE", "31")

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 10.0,
    },
    decoration = {
        blur = {
            brightness = 1.15,
            contrast = 0.97,
            noise = 0.036,
            size = 6,
            xray = false,
        },
        rounding = 8,
    },
    general = {
        border_size = 1,
        gaps_out = 8,
        snap = {
            enabled = false,
        },
    },
    gestures = {
        workspace_swipe_cancel_ratio = 0.3,
        workspace_swipe_invert = false,
        workspace_swipe_min_speed_to_force = 18,
    },
})

-- Bezier curves
hl.curve("customfast", { type = "bezier", points = { {0.329, 0.476}, {0.224, 0.983} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "customfast",
    style = "slide",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "customfast",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2.5,
    bezier = "linear",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4.79,
    bezier = "customfast",
    style = "slide",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4.0,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 2.5,
    bezier = "linear",
    style = "slide",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 4.7,
    bezier = "customfast",
    style = "slidefade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 4.9,
    bezier = "customfast",
    style = "slidefade",
})
