exec-once = systemctl --user start hyprpolkitagen
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DEKSTOP
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# QuickShell Layer Rules
source = /home/fadhil/.config/quickshell/hyprland-layer-config.conf
