general {
    lock_cmd = pidof hyprlock || hyprlock       # Runs hyprlock (or your lock screen app)
    before_sleep_cmd = loginctl lock-session    # Locks screen before system goes to sleep
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on  # Ensures display turns back on after waking up
    ignore_dbus_inhibit = false                 # Respects media player/browser inhibitors
    ignore_systemd_inhibit = false
}

# 1. Dim the screen after 2 minutes (120s)
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10%       # Save current brightness & set to 10%
    on-resume = brightnessctl -r                # Restore original brightness
}

# 2. Lock the screen after 2,5 minutes (150s)
listener {
    timeout = 150
    on-timeout = loginctl lock-session
}

# 4. Suspend the system after 10 minutes (600s)
listener {
    timeout = 600
    on-timeout = systemctl suspend              # Suspend system
}

# 5. Shutdown the system after 6 hour (21600s)
listener {
    timeout = 21600
    on-timeout = systemctl poweroff
}
