[General]
bookmarks=/home/fadhil
lastDisplay=0
maximizedWindow=true
savedPaths=/home/fadhil, /home/fadhil/Documents, /home/fadhil/go, /home/fadhil/Pictures, /home/fadhil/rofi-themes-collection, /home/fadhil/sddm, /home/fadhil/yay
windowGeometry=@Rect(0 0 1728 972)
