[Colors]
accent=#00aa00
background=#000000
background_fullscreen=#000000
folderview=#181819
folderview_topbar=#181819
icons=#ffffff
overlay=#000000
overlay_text=#000000
scrollbar=#00aa00
text=#ffffff
tid=-1
widget=#181819
widget_border=#181819
